name = "${WORKER_NAME}"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[routes]]
pattern = "${CUSTOM_DOMAIN}"
custom_domain = true

[[d1_databases]]
binding = "db"
database_name = "${D1_DATABASE_NAME}"
database_id = "${D1_DATABASE_ID}"

[[kv_namespaces]]
binding = "kv"
id = "${KV_NAMESPACE_ID}"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 * * * *"]

[vars]
domain = "${MAIL_DOMAINS}"
admin = "${ADMIN_EMAIL}"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
